
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class SaleJFrame extends javax.swing.JFrame implements PropertyListener{

    /**
     * Creates new form SaleJFrame
     */    
    ProcessSaleController psc;
    private final String[] columnNames = {"SL#","ID","Item Name","Unit Price","Quantity","Sub Total"};
    final int initialRow = 8;
    DefaultTableModel model;
    JTable saleTable;
    SaleFactory saleFactory;// = SaleFactory.getInstance();//.getInstance();
    
    @Override
    public void onPropertyEvent(int total){
        totalTextField.setText(String.valueOf(total));
        vatTextField.setText(Integer.toString(psc.getSale().getVATAmount()));
        grandTotalTextField.setText(Integer.toString(psc.getSale().getVATAmount()+total));
    }
    
    void initialize(Sale sale)
    {
        sale.addPropertyListener(this);
    }
    
    
    public SaleJFrame() {
        initComponents();
        //PrintProductSpecifications();
        idTextField.requestFocus();
    }
        
    /*void PrintProductSpecifications(){
        String output = "Currently in system\n\nSL:: ID - Name - Price\n===============\n";
        int i =0;
        for(ProductSpecification ps: saleFactory.psList){
            output+= Integer.toString(++i)+" :: "+ps.getID()+" - "+ps.getName()+" - "+ps.getPrice()+"\n";
        }
        productSpecificationsTextBox.setText(output);
    }*/
        
    private void MakeTableEmpty(){
        model.setRowCount(0);
        totalTextField.setText(" ");
        vatTextField.setText(" ");
        grandTotalTextField.setText(" ");
        model.setRowCount(initialRow);
    }
    
    private void setRowValue(SalesLineItem sli, int rowIndex){
        model.setValueAt(rowIndex+1, rowIndex, 0);
        model.setValueAt(sli.getID(), rowIndex, 1);
        model.setValueAt(sli.getName(), rowIndex, 2);
        model.setValueAt(sli.getPrice(), rowIndex, 3);
        model.setValueAt(sli.getQuantity(), rowIndex, 4);
        model.setValueAt(sli.getSubTotal(), rowIndex, 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discountButtonGroup = new javax.swing.ButtonGroup();
        NewSaleButton = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        AddItemButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        totalTextField = new javax.swing.JTextField();
        psc = new ProcessSaleController(this);
        saleFactory = SaleFactory.getInstance();
        model = new DefaultTableModel(columnNames, initialRow);
        saleTable = new JTable(model);
        saleTable.setShowGrid(true);
        saleTableScrollPane = new JScrollPane(saleTable);
        vatlLabel = new javax.swing.JLabel();
        vatTextField = new javax.swing.JTextField();
        grandTotalLabel = new javax.swing.JLabel();
        grandTotalTextField = new javax.swing.JTextField();
        totalDiscountLabel = new javax.swing.JLabel();
        totalDiscountTextField = new javax.swing.JTextField();
        bestForCustomerRadioButton = new javax.swing.JRadioButton();
        bestForStoreRadioButton = new javax.swing.JRadioButton();
        calculateDiscountButton = new javax.swing.JButton();
        absoluteThresholdStrategyCheckBox = new javax.swing.JCheckBox();
        percentStrategyCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        NewSaleButton.setBackground(new java.awt.Color(0, 255, 0));
        NewSaleButton.setLabel("New Sale");
        NewSaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSaleButtonActionPerformed(evt);
            }
        });
        NewSaleButton.setFocusTraversalKeysEnabled(false);

        infoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idLabel.setText("ID");

        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        idTextField.setFocusTraversalKeysEnabled(false);

        quantityLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quantityLabel.setText("Quantity");

        quantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextFieldActionPerformed(evt);
            }
        });
        quantityTextField.setFocusTraversalKeysEnabled(false);

        AddItemButton.setBackground(new java.awt.Color(255, 153, 0));
        AddItemButton.setLabel("Add Item");
        AddItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemButtonActionPerformed(evt);
            }
        });
        AddItemButton.setFocusTraversalKeysEnabled(false);

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quantityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddItemButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantityLabel)
                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(AddItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AddItemButton.getAccessibleContext().setAccessibleName("");

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalLabel.setText("Total");

        totalTextField.setEditable(false);
        totalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTextFieldActionPerformed(evt);
            }
        });

        saleTableScrollPane.setBackground(new java.awt.Color(255, 0, 0));
        saleTableScrollPane.setAutoscrolls(true);

        vatlLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vatlLabel.setText("VAT");

        vatTextField.setEditable(false);
        vatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatTextFieldActionPerformed(evt);
            }
        });

        grandTotalLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        grandTotalLabel.setText("Grand Total");

        grandTotalTextField.setEditable(false);
        grandTotalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandTotalTextFieldActionPerformed(evt);
            }
        });

        totalDiscountLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalDiscountLabel.setText("Discount");

        totalDiscountTextField.setEditable(false);
        totalDiscountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalDiscountTextFieldActionPerformed(evt);
            }
        });

        bestForCustomerRadioButton.setText("Best for Customer");
        bestForCustomerRadioButton.setEnabled(false);
        bestForCustomerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestForCustomerRadioButtonActionPerformed(evt);
            }
        });

        bestForStoreRadioButton.setText("Best for Store");
        bestForStoreRadioButton.setEnabled(false);

        calculateDiscountButton.setBackground(new java.awt.Color(255, 255, 204));
        calculateDiscountButton.setText("Calculate Discount");
        calculateDiscountButton.setEnabled(false);
        calculateDiscountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateDiscountButtonActionPerformed(evt);
            }
        });

        absoluteThresholdStrategyCheckBox.setText("Threshold Discount");
        absoluteThresholdStrategyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absoluteThresholdStrategyCheckBoxActionPerformed(evt);
            }
        });

        percentStrategyCheckBox.setText("Percent Discount");
        percentStrategyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentStrategyCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewSaleButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(infoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saleTableScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calculateDiscountButton)
                                    .addComponent(absoluteThresholdStrategyCheckBox)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bestForCustomerRadioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(percentStrategyCheckBox))
                                    .addComponent(bestForStoreRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(grandTotalLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(grandTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(totalDiscountLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalDiscountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vatlLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(vatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(totalLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewSaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saleTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(absoluteThresholdStrategyCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(percentStrategyCheckBox)
                        .addGap(3, 3, 3)
                        .addComponent(bestForCustomerRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bestForStoreRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculateDiscountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vatlLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalDiscountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalDiscountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grandTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grandTotalLabel))
                        .addContainerGap())))
        );

        NewSaleButton.getAccessibleContext().setAccessibleName("");
        discountButtonGroup.add(bestForCustomerRadioButton);
        discountButtonGroup.add(bestForStoreRadioButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTextFieldActionPerformed

    private void NewSaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSaleButtonActionPerformed
        // TODO add your handling code here:
        psc.makeNewSale();
        MakeTableEmpty();
    }//GEN-LAST:event_NewSaleButtonActionPerformed
   
    private void vatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vatTextFieldActionPerformed

    private void grandTotalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandTotalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grandTotalTextFieldActionPerformed

    private void totalDiscountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalDiscountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalDiscountTextFieldActionPerformed

    private void bestForCustomerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestForCustomerRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bestForCustomerRadioButtonActionPerformed

    private void calculateDiscountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateDiscountButtonActionPerformed
        // TODO add your handling code here:
        int discount = 0;
        if(psc.getSale().getSLItemsList().size()>0){
            if(bestForCustomerRadioButton.isSelected()){
                discount = psc.getSale().getDiscountAmount(DiscountType.bestForCustomerPricingStrategy);
            }else if(bestForStoreRadioButton.isSelected()){
                discount = psc.getSale().getDiscountAmount(DiscountType.bestForStorePricingStrategy);
            }else if(percentStrategyCheckBox.isSelected()){
                discount = psc.getSale().getDiscountAmount(DiscountType.percentagePricingStrategy);
            }else if(absoluteThresholdStrategyCheckBox.isSelected()){
                discount = psc.getSale().getDiscountAmount(DiscountType.absoluteThresholdPricingStrategy);
            }
            totalDiscountTextField.setText(String.valueOf(discount));
            grandTotalTextField.setText(String.valueOf(psc.getSale().getGrandTotal()));
        }
    }//GEN-LAST:event_calculateDiscountButtonActionPerformed

    private void absoluteThresholdStrategyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absoluteThresholdStrategyCheckBoxActionPerformed
        // TODO add your handling code here:
        StrategyInputCombinationUIControl();
    }//GEN-LAST:event_absoluteThresholdStrategyCheckBoxActionPerformed

    private void percentStrategyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentStrategyCheckBoxActionPerformed
        // TODO add your handling code here:
        StrategyInputCombinationUIControl();
    }//GEN-LAST:event_percentStrategyCheckBoxActionPerformed

    private void AddItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemButtonActionPerformed
        // TODO add your handling code here:
        try{
            int id = Integer.parseInt(idTextField.getText()), quantity = Integer.parseInt(quantityTextField.getText());
            psc.addItem(id, quantity);
            Sale sale = psc.getSale();
            SalesLineItem sli;
            if(sale.getLast_SLI_EntryInfo().sliType==SLI_Type.new_sli_created){
                sli = sale.getSLItem(sale.getLast_SLI_EntryInfo().positionInList);
                if(sale.getSLItemsList().size()<=initialRow){
                    setRowValue(sli, sale.getLast_SLI_EntryInfo().positionInList);
                }else{
                    Object[] o = {sale.getSLItemsList().size(), sli.getID(), sli.getName(), sli.getPrice(), sli.getQuantity(), sli.getSubTotal()};
                    model.addRow(o);
                }
            }else if(sale.getLast_SLI_EntryInfo().sliType==SLI_Type.old_sli_updated){
                sli = sale.getSLItem(sale.getLast_SLI_EntryInfo().positionInList);
                setRowValue(sli ,sale.getLast_SLI_EntryInfo().positionInList);
            }else if(sale.getLast_SLI_EntryInfo().sliType==SLI_Type.sli_creation_error){
                System.out.println("Invalid ID - Printing from UI");
            }else{
                System.out.println("Error in table manipulation");
            }
        }catch(Exception e){
            System.err.println("Enter valid (integer) ID/Quantity");
        }
        idTextField.requestFocus();
    }//GEN-LAST:event_AddItemButtonActionPerformed

    private void quantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextFieldActionPerformed
        // TODO add your handling code here:
        if(!quantityTextField.equals("")){
            AddItemButton.requestFocus();
        }
    }//GEN-LAST:event_quantityTextFieldActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
        if(!idTextField.equals("")){
            quantityTextField.requestFocus();
        }
    }//GEN-LAST:event_idTextFieldActionPerformed
    
    private void StrategyInputCombinationUIControl(){
        if(absoluteThresholdStrategyCheckBox.isSelected() && percentStrategyCheckBox.isSelected()){
            bestForCustomerRadioButton.setEnabled(true);
            bestForStoreRadioButton.setEnabled(true);
            bestForStoreRadioButton.setSelected(true);
        }else{
            bestForCustomerRadioButton.setEnabled(false);
            bestForStoreRadioButton.setSelected(false);
            bestForStoreRadioButton.setEnabled(false);
        }
        
        if(absoluteThresholdStrategyCheckBox.isSelected() || percentStrategyCheckBox.isSelected()){
            calculateDiscountButton.setEnabled(true);
        }else{
            totalDiscountTextField.setText(String.valueOf(0));
            grandTotalTextField.setText(String.valueOf(psc.getSale().getPreDiscountTotal()));
            calculateDiscountButton.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemButton;
    private javax.swing.JButton NewSaleButton;
    private javax.swing.JCheckBox absoluteThresholdStrategyCheckBox;
    private javax.swing.JRadioButton bestForCustomerRadioButton;
    private javax.swing.JRadioButton bestForStoreRadioButton;
    private javax.swing.JButton calculateDiscountButton;
    private javax.swing.ButtonGroup discountButtonGroup;
    private javax.swing.JLabel grandTotalLabel;
    private javax.swing.JTextField grandTotalTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JCheckBox percentStrategyCheckBox;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JScrollPane saleTableScrollPane;
    private javax.swing.JLabel totalDiscountLabel;
    private javax.swing.JTextField totalDiscountTextField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalTextField;
    private javax.swing.JTextField vatTextField;
    private javax.swing.JLabel vatlLabel;
    // End of variables declaration//GEN-END:variables
}
